### ISSUE TITLE
Impressed !! And Small Changes 

### ISSUE THREAD

**Issue by aswinkumar1999** [sagnik3141/Task-1#1]
Hey , I'm really impressed by your Documention and the extensiveness of it. But I see nothing in the Repository main page ... Can you add just the names of the projects in the first page  and then link it to the folders ?

**Comment by sagnik3141** [comment]
Thanks! Yeah, I'll do it asap.

**Comment by aswinkumar1999** [comment]
Closing this issue as it's resolved
